### ISSUE TITLE
Unable to install in Anaconda

### ISSUE THREAD

**Issue by bdrewr** [saforem2/ambivalent#1]
I've been trying to install this in anaconda for use within spyder and have been unable to. Using the following in anaconda's command line as administrator:

```python
pip install ambivalent
``` 

All I've gotten is the following error:
`ERROR: Could not find a version that satisfies the requirement ambivalent (from versions: none)`
`ERROR: No matching distribution found for ambivalent`

I've been able to install opinionated via the same pip install command, however.

**Comment by saforem2** [comment]
I've not gotten around to distributing it on PyPi.

In the meantime, you should be able to install with:


```bash
python3 -m pip install "git+https://github.com/saforem2/ambivalent"
```

**Comment by bdrewr** [comment]
That worked, cheers!

**Comment by saforem2** [comment]
fwiw, its now published on PyPi as well:

https://pypi.org/project/ambivalent/0.0.1/
